### ISSUE TITLE
ERREUR

### ISSUE THREAD

**Issue by Enzolus** [baptexl/Baptiste_Exilie_Adventure_Game#1]
Le code ne fonctionne pas ou n'est pas correct !!

**Comment by baptexl** [comment]
Salut Enzolus

Merci d'avoir pris le temps de me soumettre ce problème. Mais j'ai revérifié le code et il fonctionne correctement de mon côté. Il est possible que l'erreur provienne d'un environnement spécifique ou d'une configuration particulière.
